-- =============================================================================
-- SafeLPG Supabase Modular Database Schema & RLS Policies
-- =============================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =============================================================================
-- SECTION 1: TABLES DEFINITION
-- =============================================================================

-- 1. Devices Table (Linked to Supabase Auth Users)
CREATE TABLE IF NOT EXISTS public.devices (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name        TEXT NOT NULL DEFAULT 'LPG Monitor',
    location    TEXT DEFAULT 'Kitchen',
    api_key     TEXT NOT NULL UNIQUE,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Sensor Readings Table (Pushed by ESP32 via FastAPI / Supabase)
CREATE TABLE IF NOT EXISTS public.sensor_readings (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id           UUID NOT NULL REFERENCES public.devices(id) ON DELETE CASCADE,
    gas_level           NUMERIC(5, 2) NOT NULL,              -- Gas LEL % (0.00 - 100.00)
    gas_raw_adc         INTEGER,                            -- Raw ADC value (0-4095)
    temperature         NUMERIC(4, 1),                      -- °C
    humidity            NUMERIC(4, 1),                      -- %
    human_presence      BOOLEAN NOT NULL DEFAULT FALSE,     -- PIR Sensor
    distance_cm         NUMERIC(6, 2),                      -- Ultrasonic sensor
    regulator_state     BOOLEAN NOT NULL DEFAULT TRUE,      -- Reed switch (True = ON)
    door_open           BOOLEAN DEFAULT FALSE,
    relay_active        BOOLEAN DEFAULT FALSE,              -- Auto shut-off relay
    buzzer_active       BOOLEAN DEFAULT FALSE,
    battery_level       INTEGER,                            -- Battery % (0-100)
    gsm_signal_strength INTEGER,                            -- SIM800L CSQ (0-31)
    system_state        TEXT NOT NULL DEFAULT 'normal',     -- normal | warning | critical | power_cut
    timestamp           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Alerts Table (Generated by AI Service / Backend)
CREATE TABLE IF NOT EXISTS public.alerts (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id            UUID NOT NULL REFERENCES public.devices(id) ON DELETE CASCADE,
    severity             TEXT NOT NULL DEFAULT 'info',       -- info | warning | critical
    message              TEXT NOT NULL,
    leak_probability     NUMERIC(4, 3),                     -- 0.000 to 1.000
    contributing_factors TEXT[],                            -- Array of risk factors
    is_resolved          BOOLEAN NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- SECTION 2: INDEXES FOR FAST QUERIES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_devices_owner_id ON public.devices(owner_id);
CREATE INDEX IF NOT EXISTS idx_sensor_readings_device_timestamp ON public.sensor_readings(device_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_device_resolved ON public.alerts(device_id, is_resolved, created_at DESC);

-- =============================================================================
-- SECTION 3: AUTOMATIC UPDATED_AT TRIGGER
-- =============================================================================

CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_devices_updated_at ON public.devices;
CREATE TRIGGER set_devices_updated_at
BEFORE UPDATE ON public.devices
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- =============================================================================
-- SECTION 4: ROW-LEVEL SECURITY (RLS) POLICIES
-- =============================================================================

-- Enable RLS on all tables
ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sensor_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;

-- -----------------------------------------------------------------------------
-- RLS: Devices
-- -----------------------------------------------------------------------------
-- Owners can read their own devices
CREATE POLICY "Users can view own devices"
ON public.devices FOR SELECT
TO authenticated
USING (owner_id = auth.uid());

-- Owners can insert/update their own devices
CREATE POLICY "Users can manage own devices"
ON public.devices FOR ALL
TO authenticated
USING (owner_id = auth.uid())
WITH CHECK (owner_id = auth.uid());

-- -----------------------------------------------------------------------------
-- RLS: Sensor Readings
-- -----------------------------------------------------------------------------
-- Users can view readings for devices they own
CREATE POLICY "Users can view own device readings"
ON public.sensor_readings FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.devices
        WHERE devices.id = sensor_readings.device_id
        AND devices.owner_id = auth.uid()
    )
);

-- -----------------------------------------------------------------------------
-- RLS: Alerts
-- -----------------------------------------------------------------------------
-- Users can view alerts for devices they own
CREATE POLICY "Users can view own device alerts"
ON public.alerts FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.devices
        WHERE devices.id = alerts.device_id
        AND devices.owner_id = auth.uid()
    )
);

-- Users can update (resolve) alerts for devices they own
CREATE POLICY "Users can resolve own device alerts"
ON public.alerts FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.devices
        WHERE devices.id = alerts.device_id
        AND devices.owner_id = auth.uid()
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.devices
        WHERE devices.id = alerts.device_id
        AND devices.owner_id = auth.uid()
    )
);

-- =============================================================================
-- SECTION 5: REALTIME PUBLICATION SETUP
-- =============================================================================

-- Enable Realtime WebSockets for Flutter live updates
ALTER PUBLICATION supabase_realtime ADD TABLE public.sensor_readings;
ALTER PUBLICATION supabase_realtime ADD TABLE public.alerts;
